numbers = [5, 2, 8, 9]
numbers.append(6)
print(numbers)
numbers.insert(2, 4)
print(numbers)
numbers.remove(8)
print(numbers)
numbers.pop(4)
print(numbers)
numbers.index(2)
print(numbers)
print(60 in numbers)
print((numbers.count(2)))
numbers.sort()
print(numbers)
numbers.reverse()
print(numbers)
numbers2 = numbers.copy()
print(numbers2)
